apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: prod-keyvault
  namespace: prod-app

spec:
  provider: azure

  parameters:

    # Workload Identity is being used.
    usePodIdentity: "false"

    clientID: "7ce89e88-86d7-4a6b-915c-4286ef6e9b2b"

    keyvaultName: "kvakssec1977825027"

    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""

    tenantId: "e4fab72e-8c33-4ed4-b1ce-cb20b239e768"