apiVersion: v1
kind: ServiceAccount

metadata:
  name: prod-app-sa
  namespace: prod-app

  annotations:

    # Microsoft Entra managed identity used by this workload.
    azure.workload.identity/client-id: CLIENT_ID_HERE